services:
  web:
    image: napat/github_actions_demo:latest
    container_name: github_actions_demo
    ports:
      - "3000:3000"
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - caddy
networks:
  caddy:
    external: true
