name: Deploy React CSR
on:
  push:
    branches:
      - master
      - release
      - develop
      - feature/**
      - "!feature/wip/**"
  workflow_dispatch:
  pull_request:
    types:
      - opened

#env:
#  APP_VERSION: v1.0.0

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Echo env hello text
        run: |
          echo "ENV hello text: ${{ vars.HELLO_TEST }}"
      - name: Echo Secret api key
        run: |
          echo "Secret API Key: ${{ secrets.API_KEY }}"
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    # 1. เพิ่มเงื่อนไขให้ job นี้ทำงานเฉพาะ branch ที่ต้องการ deploy เท่านั้น
    if: github.ref_name == 'master' || github.ref_name == 'release' || github.ref_name == 'develop'

    # 2. กำหนด environment แบบไดนามิกตามชื่อ branch
    environment:
      name: ${{ (github.ref_name == 'master' && 'PRD') || (github.ref_name == 'release' && 'UAT') || (github.ref_name == 'develop' && 'SIT') }}

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: ./dist
      - name: Deploy to ${{ (github.ref_name == 'master' && 'PRD') || (github.ref_name == 'release' && 'UAT') || (github.ref_name == 'develop' && 'SIT') }}
        run: |
          echo "Deploying to ${{ (github.ref_name == 'master' && 'PRD') || (github.ref_name == 'release' && 'UAT') || (github.ref_name == 'develop' && 'SIT') }}..."
          echo "Using variable: ${{ vars.LOWEST_APP_VERSION }}"
          echo "Using secret: ${{ secrets.REDIS_TOKEN }}"
