name: Deploy React CSR
on:
  push:
    branches:
      - master
      - release
      - develop
      - feature/**
      - "!feature/wip/**"
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Get Github Context
        run: echo "${{ toJSON(github) }}"
