name: Matrix
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chrome, firefox, safari]
    steps:
      - name: Simulate Print node version, os, browser
        run: 'echo "Node: ${{ matrix.node }}, OS: ${{ matrix.os }}, Browser: ${{ matrix.browser }}"'
